#include "cli/package_manager.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>

#include "runtime/config_loader.h"

namespace wevoaweb {

namespace {

std::string readFileContents(const std::filesystem::path& path) {
    std::ifstream stream(path, std::ios::binary);
    if (!stream) {
        throw std::runtime_error("Unable to read package source: " + path.string());
    }

    return std::string(std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>());
}

std::string placeholderPackageTemplate(const std::string& packageName) {
    std::string functionName = packageName;
    std::replace(functionName.begin(), functionName.end(), '-', '_');
    return "// Package scaffold generated by WevoaWeb\n"
           "// Replace this with reusable routes, helpers, or components.\n\n"
           "func " +
           functionName +
           "_ready() {\n"
           "  return true\n"
           "}\n";
}

}  // namespace

PackageManager::PackageManager(FileWriter writer) : writer_(std::move(writer)) {}

PackageInstallResult PackageManager::install(const std::string& packageSpec) const {
    if (packageSpec.empty()) {
        throw std::runtime_error("Package name must not be empty.");
    }

    const std::string packageName = packageNameFromSpec(packageSpec);
    if (packageName.empty()) {
        throw std::runtime_error("Unable to determine a package name from: " + packageSpec);
    }

    const std::filesystem::path packagesDirectory = std::filesystem::current_path() / "packages";
    const std::filesystem::path destination = packagesDirectory / packageName;
    writer_.createDirectory(packagesDirectory);

    std::error_code error;
    if (std::filesystem::exists(destination, error) && !error) {
        throw std::runtime_error("Package already exists: " + destination.string());
    }

    const std::filesystem::path sourcePath = std::filesystem::absolute(packageSpec, error);
    const bool sourceExists = !error && std::filesystem::exists(sourcePath, error) && !error;

    if (sourceExists && std::filesystem::is_directory(sourcePath, error) && !error) {
        copyDirectoryContents(sourcePath, destination);
        updateProjectConfig(packageName);
        return PackageInstallResult {packageName, destination, false};
    }

    if (sourceExists && std::filesystem::is_regular_file(sourcePath, error) && !error) {
        writer_.createDirectory(destination);
        const std::filesystem::path targetFile =
            sourcePath.extension() == ".wev" ? destination / "main.wev" : destination / sourcePath.filename();
        writer_.writeTextFile(targetFile, readFileContents(sourcePath));
        updateProjectConfig(packageName);
        return PackageInstallResult {packageName, destination, false};
    }

    writer_.createDirectory(destination);
    writer_.writeTextFile(destination / "main.wev", placeholderPackageTemplate(packageName));
    updateProjectConfig(packageName);
    return PackageInstallResult {packageName, destination, true};
}

std::string PackageManager::packageNameFromSpec(const std::string& packageSpec) const {
    std::string normalized = packageSpec;
    if (!normalized.empty() && normalized.front() == '@') {
        normalized.erase(normalized.begin());
    }

    const std::filesystem::path asPath(normalized);
    std::string name = asPath.filename().string();
    if (name.empty()) {
        name = normalized;
    }
    if (name.size() >= 4 && name.substr(name.size() - 4) == ".wev") {
        name = std::filesystem::path(name).stem().string();
    }

    std::string sanitized;
    sanitized.reserve(name.size());
    for (const char ch : name) {
        const auto unsignedChar = static_cast<unsigned char>(ch);
        if (std::isalnum(unsignedChar) != 0 || ch == '_' || ch == '-') {
            sanitized.push_back(static_cast<char>(std::tolower(unsignedChar)));
        } else if (ch == '/' || ch == '\\' || std::isspace(unsignedChar) != 0) {
            if (!sanitized.empty() && sanitized.back() != '-') {
                sanitized.push_back('-');
            }
        }
    }

    while (!sanitized.empty() && sanitized.back() == '-') {
        sanitized.pop_back();
    }
    return sanitized;
}

void PackageManager::copyDirectoryContents(const std::filesystem::path& source,
                                           const std::filesystem::path& destination) const {
    namespace fs = std::filesystem;

    writer_.createDirectory(destination);
    std::error_code error;
    for (fs::recursive_directory_iterator iterator(source, fs::directory_options::skip_permission_denied, error), end;
         iterator != end;
         iterator.increment(error)) {
        if (error) {
            throw std::runtime_error("Unable to copy package source: " + source.string());
        }

        if (!iterator->is_regular_file(error) || error) {
            continue;
        }

        const auto relative = fs::relative(iterator->path(), source, error);
        if (error) {
            throw std::runtime_error("Unable to resolve package file path: " + iterator->path().string());
        }

        writer_.writeTextFile(destination / relative, readFileContents(iterator->path()));
    }
}

void PackageManager::updateProjectConfig(const std::string& packageName) const {
    const auto configPath = std::filesystem::current_path() / "wevoa.config.json";
    Value config = loadConfigFile(configPath);
    if (!config.isObject()) {
        config = Value(Value::Object {});
    }

    auto& object = config.asObject();
    Value::Array packages;
    if (const auto found = object.find("packages");
        found != object.end() && found->second.isArray()) {
        packages = found->second.asArray();
    }

    const bool alreadyListed =
        std::any_of(packages.begin(), packages.end(), [&packageName](const Value& value) {
            return value.isString() && value.asString() == packageName;
        });
    if (!alreadyListed) {
        packages.emplace_back(packageName);
    }

    object.insert_or_assign("packages", Value(std::move(packages)));
    writer_.writeTextFile(configPath, serializeJson(config));
}

}  // namespace wevoaweb
