#include "cli/package_manager.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <functional>
#include <iterator>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>

#include "runtime/config_loader.h"
#include "utils/version.h"

namespace wevoaweb {

namespace {

constexpr const char* kPackageManifestFile = "wevoa.package.json";
constexpr const char* kScaffoldVersion = "0.1.0";
constexpr const char* kCorePackageVersion = "1.0.0";
constexpr const char* kDefaultRegistryJson = R"JSON({
  "packages": {
    "auth": {
      "name": "auth",
      "version": "1.0.0",
      "source": "core://auth",
      "repo": "https://github.com/wevoa/packages-auth",
      "description": "Authentication helpers with session-backed login and registration flows.",
      "usage": "import \"@auth\"\n\nlet user = auth_register(\"demo@example.com\", \"secret123\", { role: \"admin\" })\nauth_login(\"demo@example.com\", \"secret123\")",
      "isOfficial": true,
      "dependencies": {
        "utils": "^1.0.0",
        "db": "^1.0.0"
      }
    },
    "db": {
      "name": "db",
      "version": "1.0.0",
      "source": "core://db",
      "repo": "https://github.com/wevoa/packages-db",
      "description": "Convenience helpers for configured database access in WevoaWeb apps.",
      "usage": "import \"@db\"\n\nlet total = db_scalar(\"SELECT COUNT(*) FROM users\")\nlet rows = db_query_with(\"SELECT * FROM users WHERE role = ?\", [\"admin\"])",
      "isOfficial": true
    },
    "utils": {
      "name": "utils",
      "version": "1.0.0",
      "source": "core://utils",
      "repo": "https://github.com/wevoa/packages-utils",
      "description": "Common response, string, and formatting helpers for WevoaWeb apps.",
      "usage": "import \"@utils\"\n\nreturn utils_success(\"Ready\")",
      "isOfficial": true
    }
  }
})JSON";

struct SemanticVersion {
    int major = 0;
    int minor = 0;
    int patch = 0;
};

struct PackageManifest {
    std::string name;
    std::string version;
    std::string source;
    std::string description;
    std::string repo;
    std::string usageSnippet;
    bool isOfficial = false;
    std::unordered_map<std::string, std::string> dependencies;
};

struct PackageSpec {
    std::string name;
    std::string versionConstraint;
};

std::string readFileContents(const std::filesystem::path& path) {
    std::ifstream stream(path, std::ios::binary);
    if (!stream) {
        throw std::runtime_error("Unable to read package source: " + path.string());
    }

    return std::string(std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>());
}

std::filesystem::path packageCacheDirectory() {
#ifdef _WIN32
    if (const char* localAppData = std::getenv("LOCALAPPDATA"); localAppData != nullptr && *localAppData != '\0') {
        return std::filesystem::path(localAppData) / "Wevoa" / "cache" / "packages";
    }
#endif
    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return std::filesystem::path(home) / ".wevoa" / "cache" / "packages";
    }

    return std::filesystem::current_path() / ".wevoa-cache" / "packages";
}

std::filesystem::path projectPackagesDirectory() {
    return std::filesystem::current_path() / "packages";
}

std::string normalizeImportName(std::string value) {
    if (!value.empty() && value.front() == '@') {
        value.erase(value.begin());
    }
    return value;
}

std::string sanitizePackageName(const std::string& value) {
    std::string sanitized;
    sanitized.reserve(value.size());
    for (const char ch : normalizeImportName(value)) {
        const auto unsignedChar = static_cast<unsigned char>(ch);
        if (std::isalnum(unsignedChar) != 0 || ch == '_' || ch == '-') {
            sanitized.push_back(static_cast<char>(std::tolower(unsignedChar)));
        } else if (ch == '/' || ch == '\\' || std::isspace(unsignedChar) != 0) {
            if (!sanitized.empty() && sanitized.back() != '-') {
                sanitized.push_back('-');
            }
        }
    }

    while (!sanitized.empty() && sanitized.back() == '-') {
        sanitized.pop_back();
    }
    return sanitized;
}

std::string placeholderPackageTemplate(const std::string& packageName) {
    std::string functionName = packageName;
    std::replace(functionName.begin(), functionName.end(), '-', '_');
    return "// Package scaffold generated by WevoaWeb\n"
           "// Replace this with reusable routes, helpers, or components.\n\n"
           "func " +
           functionName +
           "_ready() {\n"
           "  return true\n"
           "}\n";
}

std::string utilsPackageTemplate() {
    return "const utils = {\n"
           "  version: \"" WEVOA_VERSION "\"\n"
           "}\n"
           "\n"
           "func utils_text(value, fallback) {\n"
           "  if (value) {\n"
           "    return value\n"
           "  }\n"
           "  return fallback\n"
           "}\n"
           "\n"
           "func utils_present(value) {\n"
           "  if (value) {\n"
           "    return true\n"
           "  }\n"
           "  return false\n"
           "}\n"
           "\n"
           "func utils_lower(value) {\n"
           "  return value\n"
           "}\n"
           "\n"
           "func utils_title(value, fallback) {\n"
           "  if (value) {\n"
           "    return value\n"
           "  }\n"
           "  return fallback\n"
           "}\n"
           "\n"
           "func utils_success(message) {\n"
           "  return json({\n"
           "    success: true,\n"
           "    message: message\n"
           "  })\n"
           "}\n"
           "\n"
           "func utils_failure(message) {\n"
           "  return json({\n"
           "    success: false,\n"
           "    message: message\n"
           "  })\n"
           "}\n";
}

std::string authPackageTemplate() {
    return "import \"@utils\"\n"
           "import \"@db\"\n"
           "\n"
           "func auth_hash_password(password) {\n"
           "  return hash(password)\n"
           "}\n"
           "\n"
           "func auth_verify_password(password, digest) {\n"
           "  return verify(password, digest)\n"
           "}\n"
           "\n"
           "func auth_user() {\n"
           "  return session.get(\"auth_user\")\n"
           "}\n"
           "\n"
           "func auth_signed_in() {\n"
           "  if (session.get(\"auth_user\")) {\n"
           "    return true\n"
           "  }\n"
           "  return false\n"
           "}\n"
           "\n"
           "func auth_sign_in(user) {\n"
           "  session.set(\"auth_user\", user)\n"
           "  return user\n"
           "}\n"
           "\n"
           "func auth_sign_out() {\n"
           "  session.delete(\"auth_user\")\n"
           "  return true\n"
           "}\n"
           "\n"
           "func auth_bootstrap() {\n"
           "  db_exec(\"CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT DEFAULT 'member')\")\n"
           "  return true\n"
           "}\n"
           "\n"
           "func auth_register(email, password, profile) {\n"
           "  auth_bootstrap()\n"
           "  let role = \"member\"\n"
           "  if (profile.role) {\n"
           "    role = profile.role\n"
           "  }\n"
           "  let digest = auth_hash_password(password)\n"
           "  db_exec_with(\"INSERT INTO users (email, password_hash, role) VALUES (?, ?, ?)\", [email, digest, role])\n"
           "  let user = {\n"
           "    id: db_scalar(\"SELECT last_insert_rowid()\"),\n"
           "    email: email,\n"
           "    role: role\n"
           "  }\n"
           "  auth_sign_in(user)\n"
           "  return user\n"
           "}\n"
           "\n"
           "func auth_login(email, password) {\n"
           "  auth_bootstrap()\n"
           "  let row = db_find(\"SELECT id, email, password_hash, role FROM users WHERE email = ? LIMIT 1\", [email])\n"
           "  if (!row) {\n"
           "    return false\n"
           "  }\n"
           "  if (!auth_verify_password(password, row.password_hash)) {\n"
           "    return false\n"
           "  }\n"
           "  let user = {\n"
           "    id: row.id,\n"
           "    email: row.email,\n"
           "    role: row.role\n"
           "  }\n"
           "  auth_sign_in(user)\n"
           "  return user\n"
           "}\n"
           "\n"
           "func auth_logout() {\n"
           "  return auth_sign_out()\n"
           "}\n"
           "\n"
           "func auth_require() {\n"
           "  if (!session.get(\"auth_user\")) {\n"
           "    return redirect(\"/\")\n"
           "  }\n"
           "}\n";
}

std::string dbPackageTemplate() {
    return "const db_connection = sqlite.open(config.database.path)\n"
           "\n"
           "func db_default() {\n"
           "  return db_connection\n"
           "}\n"
           "\n"
           "func db_query(sql) {\n"
           "  return db_connection.query(sql)\n"
           "}\n"
           "\n"
           "func db_query_with(sql, params) {\n"
           "  return db_connection.query(sql, params)\n"
           "}\n"
           "\n"
           "func db_exec(sql) {\n"
           "  return db_connection.exec(sql)\n"
           "}\n"
           "\n"
           "func db_exec_with(sql, params) {\n"
           "  return db_connection.exec(sql, params)\n"
           "}\n"
           "\n"
           "func db_find(sql, params) {\n"
           "  let rows = db_connection.query(sql, params)\n"
           "  if (len(rows) == 0) {\n"
           "    return {}\n"
           "  }\n"
           "  return rows[0]\n"
           "}\n"
           "\n"
           "func db_scalar(sql) {\n"
           "  return db_connection.scalar(sql)\n"
           "}\n"
           "\n"
           "func db_scalar_with(sql, params) {\n"
           "  return db_connection.scalar(sql, params)\n"
           "}\n";
}

std::unordered_map<std::string, PackageManifest> corePackageRegistry() {
    return {
        {"utils",
         PackageManifest {"utils",
                          kCorePackageVersion,
                          "core",
                          "Common response and text helpers for WevoaWeb apps.",
                          "https://github.com/wevoa/packages-utils",
                          "import \"@utils\"\n\nreturn utils_success(\"Ready\")",
                          true,
                          {}}},
        {"auth",
         PackageManifest {"auth",
                          kCorePackageVersion,
                          "core",
                          "Authentication helpers with session-backed login and registration flows.",
                          "https://github.com/wevoa/packages-auth",
                          "import \"@auth\"\n\nlet user = auth_register(\"demo@example.com\", \"secret123\", { role: \"admin\" })\nauth_login(\"demo@example.com\", \"secret123\")",
                          true,
                          {{"utils", "^1.0.0"}, {"db", "^1.0.0"}}}},
        {"db",
         PackageManifest {"db",
                          kCorePackageVersion,
                          "core",
                          "Convenience helpers around the configured SQLite connection.",
                          "https://github.com/wevoa/packages-db",
                          "import \"@db\"\n\nlet total = db_scalar(\"SELECT COUNT(*) FROM users\")",
                          true,
                          {}}},
    };
}

std::string corePackageSource(const std::string& packageName) {
    if (packageName == "utils") {
        return utilsPackageTemplate();
    }
    if (packageName == "auth") {
        return authPackageTemplate();
    }
    if (packageName == "db") {
        return dbPackageTemplate();
    }

    throw std::runtime_error("Unknown core package: " + packageName);
}

std::string corePackageReadme(const PackageManifest& manifest) {
    std::ostringstream stream;
    stream << "# @" << manifest.name << "\n\n";
    stream << manifest.description << "\n\n";
    stream << "## Install\n\n";
    stream << "```text\nwevoa install " << manifest.name << "\n```\n\n";
    stream << "## Usage\n\n";
    stream << "```text\n" << manifest.usageSnippet << "\n```\n";
    return stream.str();
}

std::string scaffoldPackageReadme(const PackageManifest& manifest) {
    std::ostringstream stream;
    stream << "# @" << manifest.name << "\n\n";
    stream << (manifest.description.empty() ? "Local package scaffold generated by WevoaWeb." : manifest.description) << "\n\n";
    stream << "## Install\n\n";
    stream << "```text\nwevoa install " << manifest.name << "\n```\n\n";
    stream << "## Usage\n\n";
    stream << "```text\nimport \"@" << manifest.name << "\"\n```\n";
    return stream.str();
}

Value loadJsonObjectOrDefault(const std::filesystem::path& path) {
    std::error_code error;
    if (!std::filesystem::exists(path, error) || error) {
        return Value(Value::Object {});
    }

    try {
        Value value = loadConfigFile(path);
        return value.isObject() ? value : Value(Value::Object {});
    } catch (...) {
        return Value(Value::Object {});
    }
}

Value manifestToValue(const PackageManifest& manifest) {
    Value::Object object;
    object.insert_or_assign("name", Value(manifest.name));
    object.insert_or_assign("version", Value(manifest.version));
    object.insert_or_assign("source", Value(manifest.source));
    if (!manifest.description.empty()) {
        object.insert_or_assign("description", Value(manifest.description));
    }
    if (!manifest.repo.empty()) {
        object.insert_or_assign("repo", Value(manifest.repo));
    }
    if (!manifest.usageSnippet.empty()) {
        object.insert_or_assign("usage", Value(manifest.usageSnippet));
    }
    object.insert_or_assign("isOfficial", Value(manifest.isOfficial));

    Value::Object dependencies;
    for (const auto& [name, version] : manifest.dependencies) {
        dependencies.insert_or_assign(name, Value(version));
    }
    object.insert_or_assign("dependencies", Value(std::move(dependencies)));
    return Value(std::move(object));
}

PackageManifest manifestFromValue(const Value& value,
                                  const std::string& fallbackName,
                                  const std::string& fallbackVersion,
                                  const std::string& fallbackSource) {
    PackageManifest manifest {fallbackName, fallbackVersion, fallbackSource, "", "", "", false, {}};
    if (!value.isObject()) {
        return manifest;
    }

    const auto& object = value.asObject();
    if (const auto found = object.find("name"); found != object.end() && found->second.isString()) {
        manifest.name = sanitizePackageName(found->second.asString());
    }
    if (const auto found = object.find("version"); found != object.end() && found->second.isString()) {
        manifest.version = found->second.asString();
    }
    if (const auto found = object.find("source"); found != object.end() && found->second.isString()) {
        manifest.source = found->second.asString();
    }
    if (const auto found = object.find("description"); found != object.end() && found->second.isString()) {
        manifest.description = found->second.asString();
    }
    if (const auto found = object.find("repo"); found != object.end() && found->second.isString()) {
        manifest.repo = found->second.asString();
    }
    if (const auto found = object.find("usage"); found != object.end() && found->second.isString()) {
        manifest.usageSnippet = found->second.asString();
    }
    if (const auto found = object.find("isOfficial"); found != object.end() && found->second.isBoolean()) {
        manifest.isOfficial = found->second.asBoolean();
    }
    if (const auto found = object.find("dependencies");
        found != object.end() && found->second.isObject()) {
        for (const auto& [name, version] : found->second.asObject()) {
            manifest.dependencies.insert_or_assign(sanitizePackageName(name), version.toString());
        }
    }

    return manifest;
}

std::optional<SemanticVersion> parseSemanticVersion(const std::string& value) {
    SemanticVersion version;
    std::size_t offset = 0;

    const auto parsePart = [&](int& part) -> bool {
        if (offset >= value.size()) {
            return false;
        }

        std::size_t consumed = 0;
        try {
            part = std::stoi(value.substr(offset), &consumed, 10);
            offset += consumed;
            return consumed > 0;
        } catch (...) {
            return false;
        }
    };

    if (!parsePart(version.major)) {
        return std::nullopt;
    }
    if (offset >= value.size() || value[offset] != '.') {
        return std::nullopt;
    }
    ++offset;
    if (!parsePart(version.minor)) {
        return std::nullopt;
    }
    if (offset >= value.size() || value[offset] != '.') {
        return std::nullopt;
    }
    ++offset;
    if (!parsePart(version.patch)) {
        return std::nullopt;
    }

    return offset == value.size() ? std::optional<SemanticVersion>(version) : std::nullopt;
}

int compareSemanticVersions(const SemanticVersion& left, const SemanticVersion& right) {
    if (left.major != right.major) {
        return left.major < right.major ? -1 : 1;
    }
    if (left.minor != right.minor) {
        return left.minor < right.minor ? -1 : 1;
    }
    if (left.patch != right.patch) {
        return left.patch < right.patch ? -1 : 1;
    }
    return 0;
}

bool versionMatches(const std::string& constraint, const std::string& version) {
    if (constraint.empty() || constraint == "*" || constraint == "latest") {
        return true;
    }

    std::string normalized = constraint;
    // FIXED: Removes redundant array non-empty check since constraint check preceding this guarantees it.
    if (normalized.front() == '=') {
        normalized.erase(normalized.begin());
    }

    if (!normalized.empty() && normalized.front() == '^') {
        const auto minimum = parseSemanticVersion(normalized.substr(1));
        const auto candidate = parseSemanticVersion(version);
        if (!minimum.has_value() || !candidate.has_value()) {
            return version == normalized.substr(1);
        }

        return candidate->major == minimum->major && compareSemanticVersions(*candidate, *minimum) >= 0;
    }

    return version == normalized;
}

std::string pickBestVersion(const std::vector<std::string>& versions, const std::string& constraint) {
    std::vector<std::string> matches;
    std::copy_if(versions.begin(), versions.end(), std::back_inserter(matches), [&](const std::string& candidate) {
        return versionMatches(constraint, candidate);
    });

    if (matches.empty()) {
        return "";
    }

    std::sort(matches.begin(), matches.end(), [](const std::string& left, const std::string& right) {
        const auto leftSemver = parseSemanticVersion(left);
        const auto rightSemver = parseSemanticVersion(right);
        if (leftSemver.has_value() && rightSemver.has_value()) {
            return compareSemanticVersions(*leftSemver, *rightSemver) < 0;
        }
        return left < right;
    });

    return matches.back();
}

PackageSpec parsePackageSpec(const std::string& packageSpec) {
    const std::string normalized = normalizeImportName(packageSpec);
    const auto at = normalized.find('@');
    if (at == std::string::npos) {
        return PackageSpec {sanitizePackageName(normalized), ""};
    }

    return PackageSpec {sanitizePackageName(normalized.substr(0, at)), normalized.substr(at + 1)};
}

std::optional<std::filesystem::path> resolveLocalSourcePath(const std::string& packageSpec) {
    std::error_code error;
    const auto absolute = std::filesystem::absolute(packageSpec, error);
    if (error) {
        return std::nullopt;
    }

    if (std::filesystem::exists(absolute, error) && !error) {
        return absolute;
    }

    return std::nullopt;
}

void removeDirectoryIfExists(const std::filesystem::path& path) {
    std::error_code error;
    if (std::filesystem::exists(path, error) && !error) {
        std::filesystem::remove_all(path, error);
        if (error) {
            throw std::runtime_error("Unable to remove directory: " + path.string());
        }
    }
}

PackageManifest readManifest(const std::filesystem::path& packageRoot,
                             const std::string& fallbackName,
                             const std::string& fallbackVersion,
                             const std::string& fallbackSource) {
    return manifestFromValue(loadJsonObjectOrDefault(packageRoot / kPackageManifestFile),
                             fallbackName,
                             fallbackVersion,
                             fallbackSource);
}

void writeManifest(const FileWriter& writer,
                   const std::filesystem::path& packageRoot,
                   const PackageManifest& manifest) {
    writer.writeTextFile(packageRoot / kPackageManifestFile, serializeJson(manifestToValue(manifest)));
}

void ensureMainFile(const FileWriter& writer,
                    const std::filesystem::path& packageRoot,
                    const PackageManifest& manifest,
                    const std::string& fallbackSource) {
    namespace fs = std::filesystem;

    const auto mainFile = packageRoot / "main.wev";
    std::error_code error;
    if (fs::exists(mainFile, error) && !error) {
        return;
    }

    std::vector<fs::path> candidates;
    for (fs::recursive_directory_iterator iterator(packageRoot, fs::directory_options::skip_permission_denied, error), end;
         iterator != end;
         iterator.increment(error)) {
        if (error) {
            break;
        }

        if (iterator->is_regular_file(error) && iterator->path().extension() == ".wev" && !error) {
            candidates.push_back(iterator->path());
        }
    }

    if (!candidates.empty()) {
        std::sort(candidates.begin(), candidates.end());
        writer.writeTextFile(mainFile, readFileContents(candidates.front()));
        return;
    }

    writer.writeTextFile(mainFile,
                         fallbackSource.empty() ? placeholderPackageTemplate(manifest.name) : fallbackSource);
}

void ensureReadmeFile(const FileWriter& writer,
                      const std::filesystem::path& packageRoot,
                      const PackageManifest& manifest) {
    const auto readmePath = packageRoot / "README.md";
    std::error_code error;
    if (std::filesystem::exists(readmePath, error) && !error) {
        return;
    }

    if (manifest.isOfficial) {
        writer.writeTextFile(readmePath, corePackageReadme(manifest));
        return;
    }

    writer.writeTextFile(readmePath, scaffoldPackageReadme(manifest));
}

void refreshOfficialPackageFiles(const FileWriter& writer,
                                 const std::filesystem::path& packageRoot,
                                 const PackageManifest& manifest) {
    if (!manifest.isOfficial) {
        return;
    }

    writer.createDirectory(packageRoot);
    writer.writeTextFile(packageRoot / "main.wev", corePackageSource(manifest.name));
    writeManifest(writer, packageRoot, manifest);
    writer.writeTextFile(packageRoot / "README.md", corePackageReadme(manifest));
}

std::vector<std::string> cachedPackageVersions(const std::filesystem::path& cacheRoot, const std::string& packageName) {
    namespace fs = std::filesystem;

    std::vector<std::string> versions;
    std::error_code error;
    const auto packageRoot = cacheRoot / packageName;
    if (!fs::exists(packageRoot, error) || !fs::is_directory(packageRoot, error) || error) {
        return versions;
    }

    for (fs::directory_iterator iterator(packageRoot, fs::directory_options::skip_permission_denied, error), end;
         iterator != end;
         iterator.increment(error)) {
        if (error) {
            throw std::runtime_error("Unable to inspect package cache: " + packageRoot.string());
        }

        if (iterator->is_directory(error) && !error) {
            versions.push_back(iterator->path().filename().string());
        }
    }

    std::sort(versions.begin(), versions.end());
    return versions;
}

void updateProjectConfig(const FileWriter& writer, const PackageManifest& manifest) {
    const auto configPath = std::filesystem::current_path() / "wevoa.config.json";
    Value config = loadJsonObjectOrDefault(configPath);
    auto& object = config.asObject();

    Value::Array packages;
    if (const auto found = object.find("packages");
        found != object.end() && found->second.isArray()) {
        packages = found->second.asArray();
    }

    Value::Array nextPackages;
    bool replaced = false;
    for (const auto& entry : packages) {
        std::string entryName;
        if (entry.isString()) {
            entryName = sanitizePackageName(entry.asString());
        } else if (entry.isObject()) {
            const auto name = entry.asObject().find("name");
            if (name != entry.asObject().end() && name->second.isString()) {
                entryName = sanitizePackageName(name->second.asString());
            }
        }

        if (!entryName.empty() && entryName == manifest.name) {
            nextPackages.emplace_back(manifestToValue(manifest));
            replaced = true;
        } else {
            nextPackages.emplace_back(entry);
        }
    }

    if (!replaced) {
        nextPackages.emplace_back(manifestToValue(manifest));
    }

    object.insert_or_assign("packages", Value(std::move(nextPackages)));
    writer.writeTextFile(configPath, serializeJson(config));
}

void removeFromProjectConfig(const FileWriter& writer, const std::string& packageName) {
    const auto configPath = std::filesystem::current_path() / "wevoa.config.json";
    Value config = loadJsonObjectOrDefault(configPath);
    auto& object = config.asObject();

    Value::Array packages;
    if (const auto found = object.find("packages");
        found != object.end() && found->second.isArray()) {
        packages = found->second.asArray();
    }

    Value::Array nextPackages;
    for (const auto& entry : packages) {
        std::string entryName;
        if (entry.isString()) {
            entryName = sanitizePackageName(entry.asString());
        } else if (entry.isObject()) {
            const auto name = entry.asObject().find("name");
            if (name != entry.asObject().end() && name->second.isString()) {
                entryName = sanitizePackageName(name->second.asString());
            }
        }

        if (entryName != packageName) {
            nextPackages.emplace_back(entry);
        }
    }

    object.insert_or_assign("packages", Value(std::move(nextPackages)));
    writer.writeTextFile(configPath, serializeJson(config));
}

std::vector<InstalledPackageInfo> packagesFromConfig(const std::filesystem::path& configPath) {
    std::vector<InstalledPackageInfo> packages;
    const Value config = loadJsonObjectOrDefault(configPath);
    if (!config.isObject()) {
        return packages;
    }

    const auto found = config.asObject().find("packages");
    if (found == config.asObject().end() || !found->second.isArray()) {
        return packages;
    }

    for (const auto& entry : found->second.asArray()) {
        InstalledPackageInfo package;
        if (entry.isString()) {
            package.packageName = sanitizePackageName(entry.asString());
        } else if (entry.isObject()) {
            const auto& object = entry.asObject();
            if (const auto name = object.find("name"); name != object.end() && name->second.isString()) {
                package.packageName = sanitizePackageName(name->second.asString());
            }
            if (const auto version = object.find("version"); version != object.end() && version->second.isString()) {
                package.version = version->second.asString();
            }
            if (const auto source = object.find("source"); source != object.end() && source->second.isString()) {
                package.source = source->second.asString();
            }
            if (const auto description = object.find("description");
                description != object.end() && description->second.isString()) {
                package.description = description->second.asString();
            }
            if (const auto repo = object.find("repo"); repo != object.end() && repo->second.isString()) {
                package.repo = repo->second.asString();
            }
            if (const auto usage = object.find("usage"); usage != object.end() && usage->second.isString()) {
                package.usageSnippet = usage->second.asString();
            }
            if (const auto official = object.find("isOfficial");
                official != object.end() && official->second.isBoolean()) {
                package.isOfficial = official->second.asBoolean();
            }
            if (const auto dependencies = object.find("dependencies");
                dependencies != object.end() && dependencies->second.isObject()) {
                for (const auto& [dependencyName, dependencyVersion] : dependencies->second.asObject()) {
                    package.dependencies.push_back(sanitizePackageName(dependencyName) + "@" + dependencyVersion.toString());
                }
            }
        }

        if (!package.packageName.empty()) {
            packages.push_back(std::move(package));
        }
    }

    return packages;
}

InstalledPackageInfo packageInfoFromManifest(const std::filesystem::path& packageRoot) {
    const std::string packageName = packageRoot.filename().string();
    const auto manifest = readManifest(packageRoot, packageName, kScaffoldVersion, "local");
    std::vector<std::string> dependencies;
    for (const auto& entry : manifest.dependencies) {
        dependencies.push_back(entry.first + "@" + entry.second);
    }
    return InstalledPackageInfo {manifest.name,
                                 manifest.version,
                                 manifest.source,
                                 manifest.description,
                                 manifest.repo,
                                 manifest.usageSnippet,
                                 std::move(dependencies),
                                 manifest.isOfficial,
                                 packageRoot};
}

std::filesystem::path registryCacheFile() {
    return packageCacheDirectory() / "registry" / "packages.json";
}

std::string configuredRegistrySource() {
    if (const char* environment = std::getenv("WEVOA_REGISTRY_URL"); environment != nullptr && *environment != '\0') {
        return environment;
    }

    const auto configPath = std::filesystem::current_path() / "wevoa.config.json";
    const Value config = loadJsonObjectOrDefault(configPath);
    if (!config.isObject()) {
        return "";
    }

    const auto& object = config.asObject();
    if (const auto found = object.find("registry_url"); found != object.end() && found->second.isString()) {
        return found->second.asString();
    }

    if (const auto found = object.find("registry");
        found != object.end() && found->second.isObject()) {
        const auto url = found->second.asObject().find("url");
        if (url != found->second.asObject().end() && url->second.isString()) {
            return url->second.asString();
        }
    }

    return "";
}

bool isHttpUrl(const std::string& value) {
    return value.rfind("http://", 0) == 0 || value.rfind("https://", 0) == 0;
}

std::string escapeForPowerShellSingleQuotes(const std::string& value) {
    std::string escaped;
    escaped.reserve(value.size());
    for (const char ch : value) {
        if (ch == '\'') {
            escaped += "''";
        } else {
            escaped.push_back(ch);
        }
    }
    return escaped;
}

#ifndef _WIN32
std::string escapeForPosixSingleQuotes(const std::string& value) {
    std::string escaped;
    escaped.reserve(value.size() + 8);
    for (const char ch : value) {
        if (ch == '\'') {
            escaped += "'\\''";
        } else {
            escaped.push_back(ch);
        }
    }
    return escaped;
}
#endif

bool fetchUrlToFile(const std::string& url, const std::filesystem::path& destination) {
    const auto parent = destination.parent_path();
    std::error_code error;
    if (!parent.empty() && !std::filesystem::exists(parent, error)) {
        std::filesystem::create_directories(parent, error);
    }

#ifdef _WIN32
    const std::string command =
        "powershell -NoProfile -ExecutionPolicy Bypass -Command \"try { Invoke-WebRequest -Uri '" +
        escapeForPowerShellSingleQuotes(url) + "' -UseBasicParsing -OutFile '" +
        escapeForPowerShellSingleQuotes(destination.string()) + "' | Out-Null; exit 0 } catch { exit 1 }\"";
    return std::system(command.c_str()) == 0;
#else
    std::string command =
        "curl -fsSL '" + escapeForPosixSingleQuotes(url) + "' -o '" + escapeForPosixSingleQuotes(destination.string()) +
        "' >/dev/null 2>&1";
    if (std::system(command.c_str()) == 0) {
        return true;
    }
    command =
        "wget -qO '" + escapeForPosixSingleQuotes(destination.string()) + "' '" +
        escapeForPosixSingleQuotes(url) + "' >/dev/null 2>&1";
    return std::system(command.c_str()) == 0;
#endif
}

Value defaultRegistryValue() {
    return parseJsonString(kDefaultRegistryJson);
}

Value loadRegistryValue() {
    const auto cachePath = registryCacheFile();
    const auto persistRegistry = [&](const Value& value) {
        const auto parent = cachePath.parent_path();
        std::error_code error;
        if (!parent.empty() && !std::filesystem::exists(parent, error)) {
            std::filesystem::create_directories(parent, error);
        }

        std::ofstream stream(cachePath, std::ios::binary);
        if (stream) {
            const std::string serialized = serializeJson(value);
            stream.write(serialized.data(), static_cast<std::streamsize>(serialized.size()));
        }
    };
    const std::string configuredSource = configuredRegistrySource();

    auto loadIfExists = [](const std::filesystem::path& path) -> std::optional<Value> {
        std::error_code error;
        if (!std::filesystem::exists(path, error) || error) {
            return std::nullopt;
        }
        return loadJsonObjectOrDefault(path);
    };

    if (!configuredSource.empty()) {
        if (isHttpUrl(configuredSource)) {
            if (fetchUrlToFile(configuredSource, cachePath)) {
                return loadJsonObjectOrDefault(cachePath);
            }
        } else {
            std::filesystem::path configuredPath = configuredSource;
            if (configuredSource.rfind("file://", 0) == 0) {
                configuredPath = configuredSource.substr(7);
            }
            if (const auto loaded = loadIfExists(configuredPath); loaded.has_value()) {
                return *loaded;
            }
        }
    }

    if (const auto repoRegistry = loadIfExists(std::filesystem::current_path() / "registry" / "packages.json");
        repoRegistry.has_value()) {
        persistRegistry(*repoRegistry);
        return *repoRegistry;
    }

    if (const auto cached = loadIfExists(cachePath); cached.has_value()) {
        return *cached;
    }

    const Value fallback = defaultRegistryValue();
    persistRegistry(fallback);
    return fallback;
}

std::vector<InstalledPackageInfo> registryPackages() {
    std::vector<InstalledPackageInfo> packages;
    const Value registry = loadRegistryValue();
    if (!registry.isObject()) {
        return packages;
    }

    const auto found = registry.asObject().find("packages");
    if (found == registry.asObject().end() || !found->second.isObject()) {
        return packages;
    }

    for (const auto& [name, value] : found->second.asObject()) {
        const auto manifest = manifestFromValue(value, sanitizePackageName(name), kScaffoldVersion, "registry");
        std::vector<std::string> dependencies;
        for (const auto& entry : manifest.dependencies) {
            dependencies.push_back(entry.first + "@" + entry.second);
        }
        packages.push_back(InstalledPackageInfo {manifest.name,
                                                 manifest.version,
                                                 manifest.source,
                                                 manifest.description,
                                                 manifest.repo,
                                                 manifest.usageSnippet,
                                                 std::move(dependencies),
                                                 manifest.isOfficial,
                                                 {}});
    }

    std::sort(packages.begin(), packages.end(), [](const InstalledPackageInfo& left, const InstalledPackageInfo& right) {
        return left.packageName < right.packageName;
    });
    return packages;
}

std::optional<PackageManifest> registryPackageManifest(const std::string& packageName) {
    for (const auto& package : registryPackages()) {
        if (package.packageName == packageName) {
            PackageManifest manifest;
            manifest.name = package.packageName;
            manifest.version = package.version;
            manifest.source = package.source;
            manifest.description = package.description;
            manifest.repo = package.repo;
            manifest.usageSnippet = package.usageSnippet;
            manifest.isOfficial = package.isOfficial;
            for (const auto& dependency : package.dependencies) {
                const auto at = dependency.find('@');
                if (at == std::string::npos) {
                    manifest.dependencies.insert_or_assign(dependency, "*");
                } else {
                    manifest.dependencies.insert_or_assign(dependency.substr(0, at), dependency.substr(at + 1));
                }
            }
            return manifest;
        }
    }

    return std::nullopt;
}

}  // namespace

PackageManager::PackageManager(FileWriter writer) : writer_(std::move(writer)) {}

PackageInstallResult PackageManager::install(const std::string& packageSpec, bool /*globalMode*/) const {
    if (packageSpec.empty()) {
        throw std::runtime_error("Package name must not be empty.");
    }

    const auto cacheRoot = packageCacheDirectory();
    const auto packagesDirectory = projectPackagesDirectory();
    writer_.createDirectory(cacheRoot);
    writer_.createDirectory(packagesDirectory);

    const auto corePackages = corePackageRegistry();
    std::unordered_set<std::string> installing;

    std::function<PackageInstallResult(const std::string&, bool)> installPackage =
        [&](const std::string& spec, bool topLevel) -> PackageInstallResult {
        const auto localSourcePath = resolveLocalSourcePath(spec);
        PackageManifest manifest;
        std::filesystem::path cachePath;
        bool createdPlaceholder = false;
        bool installedFromCore = false;

        if (localSourcePath.has_value()) {
            std::string packageName = packageNameFromSpec(spec);
            if (packageName.empty()) {
                packageName = sanitizePackageName(localSourcePath->filename().string());
            }
            if (packageName.empty()) {
                throw std::runtime_error("Unable to determine a package name from: " + spec);
            }

            std::error_code error;
            manifest = std::filesystem::is_directory(*localSourcePath, error)
                           ? readManifest(*localSourcePath, packageName, kScaffoldVersion, "local")
                           : PackageManifest {packageName, kScaffoldVersion, "local", "", "", "", false, {}};
            manifest.name = packageName;
            cachePath = cacheRoot / manifest.name / manifest.version;
            removeDirectoryIfExists(cachePath);
            writer_.createDirectory(cachePath);

            if (std::filesystem::is_directory(*localSourcePath, error) && !error) {
                copyDirectoryContents(*localSourcePath, cachePath);
            } else if (std::filesystem::is_regular_file(*localSourcePath, error) && !error) {
                writer_.writeTextFile(cachePath / "main.wev", readFileContents(*localSourcePath));
            } else {
                throw std::runtime_error("Unsupported package source: " + localSourcePath->string());
            }

            ensureMainFile(writer_, cachePath, manifest, "");
            writeManifest(writer_, cachePath, manifest);
            ensureReadmeFile(writer_, cachePath, manifest);
        } else {
            const auto requested = parsePackageSpec(spec);
            if (requested.name.empty()) {
                throw std::runtime_error("Unable to determine a package name from: " + spec);
            }

            const std::string installKey =
                requested.name + "@" + (requested.versionConstraint.empty() ? "*" : requested.versionConstraint);
            if (!installing.insert(installKey).second) {
                return PackageInstallResult {};
            }

            const auto registryManifest = registryPackageManifest(requested.name);
            const auto coreFound = corePackages.find(requested.name);
            if (registryManifest.has_value()) {
                if (!requested.versionConstraint.empty() &&
                    !versionMatches(requested.versionConstraint, registryManifest->version)) {
                    throw std::runtime_error("Registry package " + requested.name + " does not satisfy version " +
                                             requested.versionConstraint + ".");
                }

                manifest = *registryManifest;
                cachePath = cacheRoot / manifest.name / manifest.version;

                if (manifest.source.rfind("core://", 0) == 0) {
                    installedFromCore = true;
                    const std::string coreName = manifest.source.substr(7);
                    if (coreFound == corePackages.end()) {
                        throw std::runtime_error("Registry requested unknown core package: " + coreName);
                    }
                    manifest = coreFound->second;
                    cachePath = cacheRoot / manifest.name / manifest.version;
                    removeDirectoryIfExists(cachePath);
                    refreshOfficialPackageFiles(writer_, cachePath, manifest);
                } else if (isHttpUrl(manifest.source)) {
                    if (!std::filesystem::exists(cachePath / "main.wev")) {
                        writer_.createDirectory(cachePath);
                        if (!fetchUrlToFile(manifest.source, cachePath / "main.wev")) {
                            throw std::runtime_error("Unable to fetch package source from registry: " + manifest.source);
                        }
                        writeManifest(writer_, cachePath, manifest);
                        ensureReadmeFile(writer_, cachePath, manifest);
                    }
                } else {
                    std::filesystem::path registrySourcePath = manifest.source;
                    if (manifest.source.rfind("file://", 0) == 0) {
                        registrySourcePath = manifest.source.substr(7);
                    }

                    std::error_code registryError;
                    registrySourcePath = std::filesystem::absolute(registrySourcePath, registryError);
                    if (registryError) {
                        throw std::runtime_error("Unable to resolve registry package source: " + manifest.source);
                    }

                    removeDirectoryIfExists(cachePath);
                    writer_.createDirectory(cachePath);
                    if (std::filesystem::exists(registrySourcePath, registryError) &&
                        std::filesystem::is_directory(registrySourcePath, registryError) && !registryError) {
                        copyDirectoryContents(registrySourcePath, cachePath);
                    } else if (std::filesystem::exists(registrySourcePath, registryError) &&
                               std::filesystem::is_regular_file(registrySourcePath, registryError) && !registryError) {
                        writer_.writeTextFile(cachePath / "main.wev", readFileContents(registrySourcePath));
                    } else {
                        throw std::runtime_error("Registry source does not exist: " + registrySourcePath.string());
                    }
                    writeManifest(writer_, cachePath, manifest);
                    ensureReadmeFile(writer_, cachePath, manifest);
                }
            } else {
                const auto availableVersions = cachedPackageVersions(cacheRoot, requested.name);
                const std::string selectedVersion = pickBestVersion(availableVersions, requested.versionConstraint);
                if (!selectedVersion.empty()) {
                    cachePath = cacheRoot / requested.name / selectedVersion;
                    manifest = readManifest(cachePath, requested.name, selectedVersion, "cache");
                } else {
                    const std::string scaffoldVersion =
                        requested.versionConstraint.empty() ? std::string(kScaffoldVersion) : requested.versionConstraint;
                    manifest = PackageManifest {requested.name,
                                               scaffoldVersion,
                                               "scaffold",
                                               "Scaffold package generated locally by WevoaWeb.",
                                               "",
                                               "",
                                               false,
                                               {}};
                    cachePath = cacheRoot / manifest.name / manifest.version;
                    removeDirectoryIfExists(cachePath);
                    writer_.createDirectory(cachePath);
                    writer_.writeTextFile(cachePath / "main.wev", placeholderPackageTemplate(manifest.name));
                    writeManifest(writer_, cachePath, manifest);
                    ensureReadmeFile(writer_, cachePath, manifest);
                    createdPlaceholder = topLevel;
                }
            }

            ensureMainFile(writer_, cachePath, manifest, installedFromCore ? corePackageSource(manifest.name) : "");
            ensureReadmeFile(writer_, cachePath, manifest);
            PackageInstallResult result {manifest.name, manifest.version, {}, cachePath, createdPlaceholder,
                                         installedFromCore, {}, {}};

            for (const auto& [dependencyName, dependencyVersion] : manifest.dependencies) {
                const auto dependencyResult = installPackage(dependencyName + "@" + dependencyVersion, false);
                if (!dependencyResult.packageName.empty()) {
                    result.installedDependencies.push_back(dependencyResult.packageName + "@" + dependencyResult.version);
                }
            }

            result.destination = packagesDirectory / manifest.name;
            std::error_code destinationError;
            if (std::filesystem::exists(result.destination, destinationError) && !destinationError) {
                const auto existing = readManifest(result.destination, manifest.name, "", "installed");
                if (!existing.version.empty() && existing.version != manifest.version) {
                    result.warnings.push_back("Replacing " + manifest.name + "@" + existing.version + " with " +
                                              manifest.version + ".");
                }
            }
            removeDirectoryIfExists(result.destination);
            copyDirectoryContents(cachePath, result.destination);
            refreshOfficialPackageFiles(writer_, result.destination, manifest);
            ensureMainFile(writer_, result.destination,
                           manifest,
                           installedFromCore ? corePackageSource(manifest.name) : "");
            writeManifest(writer_, result.destination, manifest);
            ensureReadmeFile(writer_, result.destination, manifest);
            updateProjectConfig(writer_, manifest);
            installing.erase(installKey);
            return result;
        }

        PackageInstallResult result {manifest.name, manifest.version, packagesDirectory / manifest.name, cachePath,
                                     createdPlaceholder, false, {}, {}};
        for (const auto& [dependencyName, dependencyVersion] : manifest.dependencies) {
            const auto dependencyResult = installPackage(dependencyName + "@" + dependencyVersion, false);
            if (!dependencyResult.packageName.empty()) {
                result.installedDependencies.push_back(dependencyResult.packageName + "@" + dependencyResult.version);
            }
        }

        std::error_code destinationError;
        if (std::filesystem::exists(result.destination, destinationError) && !destinationError) {
            const auto existing = readManifest(result.destination, manifest.name, "", "installed");
            if (!existing.version.empty() && existing.version != manifest.version) {
                result.warnings.push_back("Replacing " + manifest.name + "@" + existing.version + " with " +
                                          manifest.version + ".");
            }
        }
        removeDirectoryIfExists(result.destination);
        copyDirectoryContents(cachePath, result.destination);
        ensureMainFile(writer_, result.destination, manifest, "");
        writeManifest(writer_, result.destination, manifest);
        ensureReadmeFile(writer_, result.destination, manifest);
        updateProjectConfig(writer_, manifest);
        return result;
    };

    return installPackage(packageSpec, true);
}

PackageRemoveResult PackageManager::remove(const std::string& packageName) const {
    const std::string normalizedName = packageNameFromSpec(packageName);
    if (normalizedName.empty()) {
        throw std::runtime_error("Package name must not be empty.");
    }

    const auto destination = projectPackagesDirectory() / normalizedName;
    std::error_code error;
    if (!std::filesystem::exists(destination, error) || error) {
        throw std::runtime_error("Package is not installed: " + normalizedName);
    }

    removeDirectoryIfExists(destination);
    removeFromProjectConfig(writer_, normalizedName);
    return PackageRemoveResult {normalizedName, destination};
}

std::vector<InstalledPackageInfo> PackageManager::listInstalled() const {
    namespace fs = std::filesystem;

    std::unordered_map<std::string, InstalledPackageInfo> packagesByName;
    for (auto package : packagesFromConfig(fs::current_path() / "wevoa.config.json")) {
        package.path = projectPackagesDirectory() / package.packageName;
        packagesByName.insert_or_assign(package.packageName, std::move(package));
    }

    std::error_code error;
    const auto packagesDirectory = projectPackagesDirectory();
    if (fs::exists(packagesDirectory, error) && fs::is_directory(packagesDirectory, error) && !error) {
        for (fs::directory_iterator iterator(packagesDirectory, fs::directory_options::skip_permission_denied, error), end;
             iterator != end;
             iterator.increment(error)) {
            if (error) {
                throw std::runtime_error("Unable to inspect installed packages in: " + packagesDirectory.string());
            }

            if (!iterator->is_directory(error) || error) {
                continue;
            }

            const auto package = packageInfoFromManifest(iterator->path());
            packagesByName.insert_or_assign(package.packageName, package);
        }
    }

    std::vector<InstalledPackageInfo> packages;
    packages.reserve(packagesByName.size());
    for (auto& entry : packagesByName) {
        packages.push_back(std::move(entry.second));
    }

    std::sort(packages.begin(), packages.end(), [](const InstalledPackageInfo& left, const InstalledPackageInfo& right) {
        return left.packageName < right.packageName;
    });
    return packages;
}

std::vector<InstalledPackageInfo> PackageManager::listAvailableCore() const {
    std::vector<InstalledPackageInfo> packages;
    for (const auto& entry : corePackageRegistry()) {
        const auto& manifest = entry.second;
        std::vector<std::string> dependencies;
        for (const auto& dependency : manifest.dependencies) {
            dependencies.push_back(dependency.first + "@" + dependency.second);
        }
        packages.push_back(InstalledPackageInfo {manifest.name,
                                                 manifest.version,
                                                 manifest.source,
                                                 manifest.description,
                                                 manifest.repo,
                                                 manifest.usageSnippet,
                                                 std::move(dependencies),
                                                 manifest.isOfficial,
                                                 {}});
    }

    std::sort(packages.begin(), packages.end(), [](const InstalledPackageInfo& left, const InstalledPackageInfo& right) {
        return left.packageName < right.packageName;
    });
    return packages;
}

std::vector<InstalledPackageInfo> PackageManager::search(const std::string& query) const {
    const std::string normalizedQuery = sanitizePackageName(query);
    std::vector<InstalledPackageInfo> matches;
    for (const auto& package : registryPackages()) {
        const std::string haystack = sanitizePackageName(package.packageName + " " + package.description + " " + package.source);
        if (normalizedQuery.empty() || haystack.find(normalizedQuery) != std::string::npos) {
            matches.push_back(package);
        }
    }

    std::sort(matches.begin(), matches.end(), [](const InstalledPackageInfo& left, const InstalledPackageInfo& right) {
        if (left.isOfficial != right.isOfficial) {
            // FIXED: Removes redundant !right check. If they are not equal, then left being true implies right is false.
            return left.isOfficial;
        }
        return left.packageName < right.packageName;
    });
    return matches;
}

InstalledPackageInfo PackageManager::packageInfo(const std::string& packageName) const {
    const std::string normalizedName = sanitizePackageName(packageName);
    if (normalizedName.empty()) {
        throw std::runtime_error("Package name must not be empty.");
    }

    for (const auto& package : listInstalled()) {
        if (package.packageName == normalizedName) {
            return package;
        }
    }

    for (const auto& package : registryPackages()) {
        if (package.packageName == normalizedName) {
            return package;
        }
    }

    throw std::runtime_error("Package not found: " + normalizedName);
}

std::string PackageManager::packageNameFromSpec(const std::string& packageSpec) const {
    const auto localPath = resolveLocalSourcePath(packageSpec);
    if (localPath.has_value()) {
        std::string name = localPath->filename().string();
        if (name.size() >= 4 && name.substr(name.size() - 4) == ".wev") {
            name = std::filesystem::path(name).stem().string();
        }
        return sanitizePackageName(name);
    }

    return parsePackageSpec(packageSpec).name;
}

void PackageManager::copyDirectoryContents(const std::filesystem::path& source,
                                           const std::filesystem::path& destination) const {
    namespace fs = std::filesystem;

    writer_.createDirectory(destination);
    std::error_code error;
    for (fs::recursive_directory_iterator iterator(source, fs::directory_options::skip_permission_denied, error), end;
         iterator != end;
         iterator.increment(error)) {
        if (error) {
            throw std::runtime_error("Unable to copy package source: " + source.string());
        }

        if (!iterator->is_regular_file(error) || error) {
            continue;
        }

        const auto relative = fs::relative(iterator->path(), source, error);
        if (error) {
            throw std::runtime_error("Unable to resolve package file path: " + iterator->path().string());
        }

        writer_.writeTextFile(destination / relative, readFileContents(iterator->path()));
    }
}

}  // namespace wevoaweb
